/**
 * Playwright Framework - ScreenshotUtil
 * <p>
 * Utility class for capturing screenshots during test execution.
 * Screenshots are stored inside the run-specific report folder
 * generated by {@link utils.ConfigManager#getReportDir()}.
 * </p>
 *
 * <p>Features:</p>
 * <ul>
 *   <li>Captures full-page screenshots using Playwright {@link com.microsoft.playwright.Page}.</li>
 *   <li>Generates timestamped filenames for uniqueness.</li>
 *   <li>Organizes screenshots into a {@code /screenshots} subfolder under the report directory.</li>
 *   <li>Returns screenshot path with forward slashes (for ExtentReports compatibility).</li>
 * </ul>
 *
 * <p><b>Usage Example:</b></p>
 * <pre>{@code
 * Page page = context.newPage();
 * page.navigate("https://example.com");
 *
 * String screenshotPath = ScreenshotUtil.takeScreenshot(page, "HomePage_Loaded");
 * ReportManager.stepPass("Homepage loaded successfully", screenshotPath);
 * }</pre>
 *
 * <p><b>Author:</b> Venkataraghavan</p>
 * <p><b>Copyright:</b> © 2025 Perficient</p>
 */
package utils;

import com.microsoft.playwright.Page;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Utility class for capturing and saving Playwright screenshots.
 */
public class ScreenshotUtil {

    /**
     * Captures a full-page screenshot and saves it in the report directory.
     * <p>
     * The screenshot filename includes the step name (sanitized for safe characters)
     * and a timestamp for uniqueness. Files are stored under:
     * {@code <reportDir>/screenshots/stepName_timestamp.png}.
     * </p>
     *
     * @param page     the Playwright {@link Page} instance
     * @param stepName a descriptive name for the screenshot (used in filename)
     * @return absolute path of the saved screenshot (forward slashes for ExtentReports)
     */
    public static String takeScreenshot(Page page, String stepName) {
        try {
            // Sanitize step name (only alphanumeric, dash, underscore allowed)
            String safeStepName = stepName.replaceAll("[^a-zA-Z0-9-_]", "_");

            // Generate timestamp
            String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmssSSS").format(new Date());

            // Final filename
            String fileName = safeStepName + "_" + timestamp + ".png";

            // Target directory under reports/run_xxx/screenshots
            String screenshotDir = ConfigManager.getReportDir() + "/screenshots";
            Path screenshotPath = Path.of(screenshotDir, fileName);
            Files.createDirectories(screenshotPath.getParent());

            // Capture screenshot
            page.screenshot(new Page.ScreenshotOptions()
                    .setPath(screenshotPath)
                    .setFullPage(true));

            // Return normalized path for ExtentReports (forward slashes)
            return screenshotPath.toAbsolutePath().toString().replace("\\", "/");
        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
}
